private ["_charge"];
PAPchargeZone setPos getPos trash;
{hint "Run... 5";} remoteExec ["bis_fnc_call", 0];
sleep 1;
{hint "Run... 4";} remoteExec ["bis_fnc_call", 0];
sleep 1;
{hint "Run... 3";} remoteExec ["bis_fnc_call", 0];
sleep 1;
{hint "Run... 2";} remoteExec ["bis_fnc_call", 0];
sleep 1;
{hint "Run... 1";} remoteExec ["bis_fnc_call", 0];
_charge = "DemoCharge_Remote_Ammo_Scripted" createVehicle (getMarkerPos "PAPexplosion");
sleep 1;
_charge setDamage 1;
sleep 0.4;
{hint "Please pack-a-punch responsibly...";} remoteExec ["bis_fnc_call", 0];
PAPWallIntact setPos getPos trash;
PAPMinesSign setPos getPos trash;
PAPWallDestroyedB hideObjectGlobal false;
PAPKillBox setPos getPos trash;
w7SandBags setPos getPos trash;
w7SandBags2 setPos getPos trash;
zbreach7 setPos getPos trash;
w7Post1 setPos getPos trash;
w7Post2 setPos getPos trash;
zwindow7b1 setPos getPos trash;
zwindow7b2 setPos getPos trash;
zwindow7b3 setPos getPos trash;
zwindow7b4 setPos getPos trash;
zwindow7b5 setPos getPos trash;
PAPcollisionwall1 setPos getPos trash;
PAPcollisionwall2 setPos getPos trash;
PAPcollisionwall3 setPos getPos trash;